export * from "./Icon.styles"
export { default as LogoIcon } from "./LogoIcon"
export { default as MenuIcon } from "./MenuIcon"
export { default as CloseIcon } from "./CloseIcon"
export { default as GithubIcon } from "./GithubIcon"
export { default as LinkedInIcon } from "./LinkedInIcon"
